name: Update

on:
  schedule:
    # Esegue ogni 2 ore al minuto 30 (es. 00:30, 02:30, 04:30...)
    - cron: '30 */2 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG script
        run: python epg.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .
          
          # Commit solo se ci sono modifiche
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update" && git push)
